# Generated by Django 3.1.7 on 2021-04-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='Git_URL',
        ),
        migrations.AddField(
            model_name='project',
            name='website_URL',
            field=models.URLField(blank=True),
        ),
    ]
